[package]
name = "open-desktop-thermal-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.0"
egui_extras = "0.24.1"
env_logger = "0.10.1"

nokhwa = {git ="https://github.com/alufers/nokhwa.git", branch = "fix/0.10.3-fix-linux-build", features = ["input-v4l", "output-threaded"]}
once_cell = "1.18.0"
regex = "1.10.2"




[dependencies.winit]
features = ["wayland"]
